name: card_swiper
description: swiper/carousel for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 2.0.4
homepage: https://github.com/TheAnkurPanchani/flutter_swiper

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=3.7.0 <4.0.0"

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
